### ISSUE TITLE
GitHub Actions: ':app:lintVitalRelease'. > ':image_picker_android:debugUnitTestRuntimeClasspath'.

### ISSUE THREAD

**Issue by kenaitian** [maierj/fastlane-action-test#1]
1. Execution failed for task ':app:lintVitalRelease'.
2. Execution failed for task ':app:validateSigningRelease'.
> Keystore file not set for signing config release"

Wilkenson Francois <wfrancois@lessimp.com> [#12](https://issuetracker.google.com/issues/234820023#comment12)Jun 5, 2022 06:39PM

Solution/Error:
1. commented out the only lintOptions under "buildTypes { release {..." of android/app/build.grade as follows:
    buildTypes {
        release {
#            lintOptions {
#                disable 'InvalidPackage'
#                disable "Instantiatable"
#                checkReleaseBuilds false
#                abortOnError false
#            }
            signingConfig signingConfigs.release
        }
    }

2. Made sure my keys.properties and key.jks files were inside the android/app folder since the ':app:lintVitalRelease' is related to some path via /home/runner/work/lessimp/lessimp/android/app 
keys.properties syntax where all others failed:
     storePassword=XXXXXX
     keyPassword=XXXXXX
     keyAlias=gpgKey
     storeFile=key.jks 

3. Two jobs were expected from the android-cd.yml file:
a. Building Android --> SUCCEEDED 
b. Deploying to playstore --> FAILED: See Screen Shot:
Run Fastlane:
Run maierj/fastlane-action@v1.4.0
  with:
    lane: closed_beta
    subdirectory: android
  env:
    JAVA_HOME_12.0.2_x64: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/12.0.2/x64
    JAVA_HOME_12_0_2_X64: /opt/hostedtoolcache/jdk/12.0.2/x64
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/3.0.1-stable/x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/3.0.1-stable/x64/.pub-cache
Executing lane closed_beta on Linux.
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
Moving to subdirectory android
Successfully installed bundler-2.3.15
Parsing documentation for bundler-2.3.15
Installing ri documentation for bundler-2.3.15
Done installing documentation for bundler after 0 seconds
1 gem installed
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /home/runner/work/lessimp/lessimp/android/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
        from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
        from /usr/local/bin/bundle:23:in `<main>'
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /home/runner/work/lessimp/lessimp/android/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
        from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
        from /usr/local/bin/bundle:23:in `<main>'
Error: Error: Executing lane closed_beta failed.
Error: Executing lane closed_beta failed.

4. YouTube Solution after Step 3b but it defeats the purpose for Fastlane with GitHub Actions: [https://youtu.be/VHzWQJKvol0](https://www.google.com/url?q=https://youtu.be/VHzWQJKvol0&sa=D&source=buganizer&usg=AOvVaw1g35ORUxJXccM_AoJwtVpC)

Screen Shot 2022-06-05 at 6.32.20 PM.png

275 KB [View](https://issuetracker.google.com/action/issues/234820023/attachments/37542811?download=false)[ Download](https://issuetracker.google.com/action/issues/234820023/attachments/37542811?download=true)

**Comment by maierj** [comment]
This has nothing to do with this repository.
